stages:
  - build
  - lint
  - scan
  - deploy

variables:
  PROJECT_NAME: auto-snab-orders-assistant
  IMAGE_NAME: cr.yandex/${YC_REGISTRY_BACK_ID}/${PROJECT_NAME}
  CONTAINER_NAME: auto-snab-orders-assistant
  NETWORK_NAME: auto-snab
  DEPLOY_PORT: "8002"
  CONTAINER_PORT: "8000"
  EXTRA_BEFORE_SCRIPT: >-
    cat "$GOOGLE_SERVICE_ACCOUNT_JSON"
    | docker run --rm -i
    -v "$CI_PROJECT_DIR/docker:/compose"
    alpine sh -c 'rm -rf /compose/secrets/google-service-account.json &&
    mkdir -p /compose/secrets &&
    cat > /compose/secrets/google-service-account.json &&
    chmod 444 /compose/secrets/google-service-account.json'

include:
  - project: 'antipov-devops/ci-templates'
    file: '/build-hatch.yml'
    ref: main
  - project: 'antipov-devops/ci-templates'
    file: '/security-scan.yml'
    ref: main
  - project: 'antipov-devops/ci-templates'
    file: '/docker-build.yml'
    ref: main
  - project: 'antipov-devops/ci-templates'
    file: '/deploy.yml'
    ref: main
