x-app-production: &app-production
  environment:
    APP_ENV: production
  read_only: true
  tmpfs:
    - /tmp:size=64m,mode=1777
  cap_drop:
    - ALL
  pids_limit: 512

services:
  postgres:
    restart: always
    security_opt:
      - no-new-privileges:true

  redis:
    restart: always
    security_opt:
      - no-new-privileges:true

  migrate:
    <<: *app-production
    security_opt:
      - no-new-privileges:true

  api:
    <<: *app-production

  worker:
    <<: *app-production

  beat:
    <<: *app-production
